### ISSUE TITLE
Interested in self hosting for friends - how to serve?

### ISSUE THREAD

**Issue by elsherbini** [zetter/multicrosser#16]
Hello, this project looks really cool and I'm interested in self-hosting it for some friends. My plan was to add some hard coded crosswords rather than using the scraper, like you did in zetter@954c337.

I'm a total ruby and rails noob, and I can't tell how you are serving the site for local dev. I've tried `./bin/setup` followed by `rails server` and `./bin/webpack-dev-server`.  `./bin/setup` gives and error saying that rake doesn't know how to do setup:db.

How should I serve the site locally for testing? And are there any differences between that and production?

**Comment by zetter** [comment]
Hi @elsherbini 👋 

Sorry, I hadn't kept the `./bin/setup` file up to date- the database setup step isn't needed but the commented out yarn step is. Please pull the latest changes and try again.

I've also updated the [Readme](https://github.com/zetter/multicrosser#setup) file to list all the steps. You will need to have a Redis server running if you haven't already.

In production I run the `web` command in the [Procfile](https://github.com/zetter/multicrosser/blob/master/Procfile) to start the server. You may be able to deploy the app to Heroku with no code changes (I use the similar Dokku service on my own server). You'll also need to:
+ Add the `REDIS_URL` environment variable to point to a Redis server (there's a free add-on for this if you choose to use Heroku). 
+ Set the `WEBSOCKET_URL` to point to Rail's WebSocket server on your deployed application e.g: `wss://multicrosser.chriszetter.com/cable` (you will need to redeploy for this to take effect).

Do let me know if the setup steps still aren't working or if you get stuck deploying your changes somewhere.

I'd love to look at any code changes that might make using other crosswords easier.
