### ISSUE TITLE
Crossword answers aren't being persisted

### ISSUE THREAD

**Issue by daniel-price** [zetter/multicrosser#68]
Hey Chris, 

Firstly awesome work and website - my friends and I use it every day!

Looks like your hosted version (https://multicrosser.chriszetter.com) broke yesterday.

If you type in a clue and then refresh the page, the clue is no longer there.

**Comment by zetter** [comment]
Hi @daniel-price, it's great to hear you find the tool useful.

Thank for letting know about the issue (the server ran out of disk space). I've fixed it.
